source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JJMaterialTextField_Example', :exclusive => true do
  pod "JJMaterialTextField", :path => "../"
end

target 'JJMaterialTextField_Tests', :exclusive => true do
  pod "JJMaterialTextField", :path => "../"

  
end
